# Use a base image
FROM node:18

# Set working directory
WORKDIR usr/server

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server side code
COPY . ./

# Expose the port the app runs on
EXPOSE 4000

# Command to run the app
CMD ["npm", "start"]